version: 0.1

phases:
  pre_build:
    commands:
      - docker build -t test-app ./api-server-mongo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t test-app ./api-server-mongo
      - docker run --name test-app -d test-app
      - docker exec test-app npm run test