# create a docker-compose.yml file
version: "2"
services:
  # api server
  proxy:
    build: ./nginx-naxsi-proxy
    ports:
      ["80:80"]
    links:
      [mongo-api]
  mongo-api:
    build: ./api-server-mongo
    volumes:
      - ./api-server-mongo/:/app
    links:
      [mongo]
  # mongo db container
  mongo:
    image: mongo
    ports:
      ["27017:27017"]
