# create a docker-compose.yml file
version: "2"
services:
  proxy:
    build: ./nginx-naxsi-proxy
    ports:
      ["80:80"]
    links:
      ["mongo-api"]
  mongo-api:
    build: ./api-server-mongo
    ports: 
      ["8000"]
    links:
      ["mongodb"]
    environment:
      - DOCKER=true
  # still doesn't really work, need to bash into the container and add the user manually
  mongodb:
    build: ./mongo-db
    ports: 
      ["27017:27017"]
    command: mongod --auth
